import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FaSquareGithub } from "react-icons/fa6";
import { IoLogoVercel } from "react-icons/io5";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Imagerie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}

<footer>
  <div className="py-8 text-white bg-black">
    <div className="container mx-auto flex flex-col md:flex-row justify-between items-center px-6">
      <div className="flex flex-col items-center md:items-start mb-6 md:mb-0">
        <h1 className="text-3xl font-bold mb-2">Traitement d'image</h1>
        <ul className="flex space-x-6">
          <li className="flex flex-col items-center"><FaSquareGithub className="text-3xl mb-1"/><span className="text-sm">GitHub</span></li>
          <li className="flex flex-col items-center"><IoLogoVercel className="text-3xl mb-1"/><span className="text-sm">Vercel</span></li>
        </ul>
      </div>
      <ul className="text-center md:text-right">
        <li className="text-lg">© ic.00</li>
        <li className="text-lg">Terms & conditions</li>
        <li className="text-lg">Privacy Policy</li>
      </ul>
    </div>
    <div className="mt-6 flex justify-center">
      <input type="text" placeholder="Entrez un nom" className="   outline-none placeholder:text-lg pl-4 border h-10 w-1/3 bg-white border-white rounded-md mr-3 text-black" />
      <button className="cursor-pointer hover:bg-white hover:text-black  text-white font-semibold  h-10 px-4 rounded-xl bg-black bg-opacity-30 hover:bg-opacity-50 transition-all" type="submit">Envoyer</button>
    </div>
    <p className="mt-8 text-center text-lg font-mono opacity-80">
      contactez nous par email 📧
    </p>
  </div>
</footer>

      </body>
    </html>
  );
}
